<h1><span style="color: #cc0000">HELLO!</span> Blog App <a title="Back to blog" style="float:right" href="/">&rarr;</a></h1>
<hr>

<h2>Add a new post</h2>
<small>WriteController::addAction()</small>
<?php
	$form = $this->form;
	$form->setAttribute('action', $this->url());
	$form->prepare();

	echo $this->form()->openTag($form);
	echo $this->formCollection($form);
	echo $this->form()->closeTag();
?>

<style>
	form label, form label span
	{
		display: block;
	}
	form input[type="text"]
	{
		width: 100%;
	}
	form textarea
	{
		width: 100%;
		height: 100px;
	}
</style>