<h1><span style="color: #cc0000">HELLO!</span> Blog App <a title="Back to blog" style="float:right" href="/">&rarr;</a></h1>
<hr>

<h2>Edit the post</h2>
<small>WriteController::editAction()</small>
<?php
	$form = $this->form;
	$form->setAttribute('action', $this->url('blog/edit', array(), true));
	$form->prepare();

	$form->get('submit')->setValue('Update Post');

	echo $this->form()->openTag($form);
	echo $this->formCollection($form);
	echo $this->form()->closeTag();
?>

<style>
	article a
	{
		color: #333333;
	}
	article a:hover, h1 a, h1 a:hover
	{
		color: #cc0000;
	}
	form label, form label span
	{
		display: block;
	}
	form input[type="text"]
	{
		width: 100%;
	}
	form textarea
	{
		width: 100%;
		height: 100px;
	}
</style>